import React, { useState } from "react";
import { Box, Typography, Snackbar, Alert } from "@mui/material";
import { FaInstagram, FaEnvelope, FaFacebookF, FaLinkedinIn, FaPinterestP, FaPhoneAlt, FaYoutube } from "react-icons/fa";
import logo from "../assets/long-white.svg";
import "../styles/Footer.css";

const Footer = () => {
  const [snackbarOpen, setSnackbarOpen] = useState(false);
  const [snackbarMessage, setSnackbarMessage] = useState("");
  const [snackbarSeverity, setSnackbarSeverity] = useState("success");
  const [isLoading, setIsLoading] = useState(false);

  const API_URL = process.env.REACT_APP_API_URL || "https://printfrall.onrender.com";

  const handleSubscribe = async (e) => {
    e.preventDefault();
    const email = e.target.email.value.trim();

    if (!email) {
      setSnackbarMessage("Please enter an email address");
      setSnackbarSeverity("error");
      setSnackbarOpen(true);
      return;
    }

    setIsLoading(true);

    try {
      const response = await fetch(`${API_URL}/subscribe`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ email }),
      });

      // Safely check content type header to prevent JSON parsing crashes
      const contentType = response.headers.get("content-type");
      let data;
      if (contentType && contentType.includes("application/json")) {
        data = await response.json();
      } else {
        const rawText = await response.text();
        data = { success: response.ok, message: rawText, error: rawText };
      }


      if (response.ok && data.success === true) {
        setSnackbarMessage(data.message || "✅ Successfully subscribed to newsletter!");
        setSnackbarSeverity("success");
        e.target.reset();
      } else {
        // Capture specific error strings generated by your backend validation rules
        setSnackbarMessage(data.error || "Failed to subscribe. Please try again.");
        setSnackbarSeverity(response.status === 400 ? "warning" : "error");
      }
    } catch (error) {
      console.error("Network trace:", error);
      setSnackbarMessage("Network error. Please check your connection.");
      setSnackbarSeverity("error");
    } finally {
      setIsLoading(false);
      setSnackbarOpen(true);
    }
  };

  const handleCloseSnackbar = (event, reason) => {
    if (reason === 'clickaway') return;
    setSnackbarOpen(false);
  };

  return (
    <Box className="footer">
      <Box className="footer-container">
        {/* Logo Section with Tagline */}
        <Box className="footer-logo-container">
          <img src={logo} alt="PrintfrAll Logo" className="footer-logo" />
          <Typography className="footer-tagline">Your Printing Partner</Typography>
        </Box>

        {/* Our Company */}
        <Box className="footer-column">
          <Typography className="footer-heading">Our Company</Typography>
          <a href="/about">About us</a>
          <a href="mailto:printfrall@gmail.com?subject=Job Application">Careers</a>
          <a href="/blog">Blog</a>
        </Box>

        {/* Important Links */}
        <Box className="footer-column">
          <Typography className="footer-heading">Important Links</Typography>
          <a href="/privacy-policy">Privacy Policy</a>
          <a href="/delivery-return">Delivery & Return Policy</a>
          <a href="/terms-conditions">Terms & Conditions</a>
        </Box>

        {/* Contact Info & Social Media */}
        <Box className="footer-column contact-info">
          <Typography className="footer-heading">Contact</Typography>
          <Box className="contact-item">
            <FaPhoneAlt className="contact-icon" />
            <a href="tel:+919319042075">+91 9319042075</a>
          </Box>
          <Box className="contact-item">
            <FaEnvelope className="contact-icon" />
            <a href="mailto:printfrall@gmail.com">printfrall@gmail.com</a>
          </Box>
          
          <Box className="map-container">
            <iframe
              title="PrintfrAll Location"
              src="https://maps.google.com/maps?q=Uttam%20Nagar,New%20Delhi&t=&z=13&ie=UTF8&iwloc=&output=embed" 
              width="100%"
              height="150"
              style={{ border: 0, borderRadius: "8px" }}
              allowFullScreen=""
              loading="lazy"
            ></iframe>
          </Box>
        </Box>

        {/* Newsletter Section */}
        <Box className="footer-column newsletter-column">
          <Typography className="footer-heading">Subscribe to our Newsletter</Typography>
          <form className="newsletter-form" onSubmit={handleSubscribe}>
            <input
              type="email"
              name="email"
              placeholder="Enter your email"
              className="newsletter-input"
              required
              disabled={isLoading}
            />
            <button type="submit" className="newsletter-button" disabled={isLoading}>
              {isLoading ? "Subscribing..." : "Subscribe"}
            </button>
          </form>

          <Typography className="footer-heading social-heading">Follow us</Typography>
          <Box className="footer-social">
            <a href="https://instagram.com/printfrall" target="_blank" rel="noopener noreferrer" aria-label="Instagram">
              <FaInstagram className="social-icon instagram" />
            </a>
            <a href="https://facebook.com/" target="_blank" rel="noopener noreferrer" aria-label="Facebook">
              <FaFacebookF className="social-icon facebook" />
            </a>
            <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">
              <FaLinkedinIn className="social-icon linkedin" />
            </a>
            <a href="https://youtube.com/PrintfrAll" target="_blank" rel="noopener noreferrer" aria-label="Youtube">
              <FaYoutube className="social-icon youtube" />
            </a>
            <a href="https://pinterest.com/printfrall" target="_blank" rel="noopener noreferrer" aria-label="Pinterest">
              <FaPinterestP className="social-icon pinterest" />
            </a>
          </Box>
        </Box>
      </Box>

      {/* Copyright Section */}
      <Typography className="footer-text">
        © {new Date().getFullYear()} <a href="/" className="footer-brand">PrintfrAll</a>. All rights reserved.
      </Typography>

      {/* Fixed Snackbar configuration */}
      <Snackbar
        open={snackbarOpen}
        autoHideDuration={4000}
        onClose={handleCloseSnackbar}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert 
          onClose={handleCloseSnackbar} 
          severity={snackbarSeverity}
          variant="filled"
          sx={{ width: '100%', fontSize: '0.95rem', fontWeight: 500 }}
        >
          {snackbarMessage}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default Footer;